### ISSUE TITLE
Mic volume control support

### ISSUE THREAD

**Issue by Vafa-Andalibi** [marioortizmanero/polybar-pulseaudio-control#25] opened 2020-04-27 15:48 UTC
Is there anyway to control the microphone volume?

**Comment by marioortizmanero** [comment] 2020-04-27 16:09
Not right now, but it's definitely a good idea!

The thing is that currently, the Polybar module already has all the available keybindings in use, except for the double click ones. When I currently have to modify my microphone's volume I just do it inside Pavucontrol, because it's not something I do often anyway.

If I were to fully implement microphone support, I'd also have to add them in the output, similarly to how  it currently works for sinks: `<vol-icon> X% <sink-icon> <sink-name> || <vol-icon> <mic-vol> <mic-icon> <mic-name>`. That way, you could also switch between microphones easily and later modify their volume. But it's definitely too much output, and again, there wouldn't be enough keys to easily control it.

I think the best way to do it is to have the script support both sinks and microphones, and being able to choose between which one to use (not both at the same time). But they'd be used the same way, so it'd be quite easy to just have two modules in Polybar; one for sinks, and another for microphones.

What do you think?

**Comment by Vafa-Andalibi** [comment] 2020-04-27 16:11
yes that's a good idea. I'm actually trying to create a popup module for pavucontrol for now.

**Comment by marioortizmanero** [comment] 2020-04-27 16:34
Heh, I didn't even know popup modules were a thing. Do let me know if you end up finishing it to mention it in the README

I'll work on this once I have more time, it's definitely an interesting feature. The problem is that you'd currently need two copies of this script to have different configurations. I've opened an issue with a possible solution at #26. The part where you choose between sink and microphone support could also be easily configured easily with #2

**Comment by marioortizmanero** [comment] 2021-04-23 22:20
By the way, now that we have flags in the script instead of globals, this could be implemented right now as a `--microphone` flag (for example) that enables sources instead of sinks in the script. I might not have enough time for this myself so anyone interested in this is free to try themselves :)

**Comment by marioortizmanero** [comment] 2022-07-03 13:06
Closed by #64. Thanks to @Aerion!

**Closed as completed by marioortizmanero** 2022-07-03 13:06 UTC
Labels: enhancement
